Repository JuliaPlots/Plots.jl, pull requests merged in 2021-08, with the labels that each got.

#3634 Allow relative positioning of annotations
  src/components.jl
  test/test_components.jl
Labels: enhancement

#3749 Code style - format
  .JuliaFormatter.toml
  .github/workflows/benchmark.yml
  .github/workflows/ci.yml
  .github/workflows/format.yml
  src/Plots.jl
  src/animation.jl
  src/arg_desc.jl
  src/args.jl
  src/axes.jl
  src/backends.jl
  src/backends/deprecated/pgfplots.jl
  src/backends/gaston.jl
  src/backends/gr.jl
  src/backends/hdf5.jl
  src/backends/inspectdr.jl
  src/backends/pgfplotsx.jl
  src/backends/plotly.jl
  src/backends/plotlyjs.jl
  src/backends/pyplot.jl
  src/backends/unicodeplots.jl
  src/backends/web.jl
  src/colorbars.jl
  src/components.jl
  src/examples.jl
  src/fileio.jl
  src/ijulia.jl
  src/init.jl
  src/layouts.jl
  src/legend.jl
  src/output.jl
  src/pipeline.jl
  src/plot.jl
  src/plotattr.jl
  src/precompile_includer.jl
  src/recipes.jl
  src/shorthands.jl
  src/subplots.jl
  src/themes.jl
  src/types.jl
  src/utils.jl
  test/imgcomp.jl
  test/integration_dates.jl
  test/runtests.jl
  test/test_axes.jl
  test/test_axis_letter.jl
  test/test_components.jl
  test/test_hdf5plots.jl
  test/test_pgfplotsx.jl
  test/test_pipeline.jl
  test/test_recipes.jl
  test/test_shorthands.jl
Labels: enhancement

#3750 UnicodePlots: fix setting linecolor
  src/backends/unicodeplots.jl
  src/precompile_includer.jl
Labels: bug

#3761 CI: julia-uploadcodecov is deprecated
  .github/workflows/ci.yml
  .github/workflows/codecov.yml
  .github/workflows/format.yml.disabled
Labels: CI

#3757 Plotly: Enable specified contour values for ranges; warn otherwise
  src/arg_desc.jl
  src/args.jl
  src/backends/plotly.jl
  src/backends/pyplot.jl
  test/runtests.jl
  test/test_contours.jl
  test/test_plotly.jl
Labels: Plotly

#3756 improve axis decorations
  src/backends/pgfplotsx.jl
Labels: PGFPlotsX

#3772 sanitize axis strings in pgfplotsx
  src/backends/pgfplotsx.jl
Labels: PGFPlotsX

#3774 UnicodePlots: heatmap support
  src/backends.jl
  src/backends/unicodeplots.jl
  src/examples.jl
Labels: UnicodePlots

#3775 Cache axis args in a dictionary
  Project.toml
  src/args.jl
  src/axes.jl
  src/backends.jl
  src/backends/deprecated/pgfplots.jl
  src/backends/gaston.jl
  src/backends/gr.jl
  src/backends/pgfplotsx.jl
  src/backends/plotly.jl
  src/backends/pyplot.jl
  src/components.jl
  src/pipeline.jl
  src/utils.jl
Labels: performance
