Repository JuliaPlots/Plots.jl, pull requests merged in 2021-07, with the labels that each got.

#3590 GR: 3D, warn on invalid rotation or tilt
  src/backends/gr.jl
Labels: GR

#3177 Gnuplot (GASTON) backend testing
  src/backends.jl
  src/backends/gaston.jl
  src/init.jl
Labels: enhancement, help wanted

#3577 GR: rework automatic major/minor ticks for log scales
  src/axes.jl
  src/examples.jl
Labels: GR, enhancement

#3612 GR: add support for mesh3d
  src/backends.jl
  src/backends/gr.jl
  src/examples.jl
Labels: GR, enhancement

#2690 add the plot_title
  src/arg_desc.jl
  src/args.jl
  src/backends/pgfplotsx.jl
  src/pipeline.jl
  src/plot.jl
Labels: enhancement

#3659 Make tickmarks the same length for both axes in GR 2D plots
  src/axes.jl
Labels: GR

#3667 Add new gnuplot capabilities (surface, contour, contour3d, scatter3d, wireframe, heatmap, ...)
  src/backends.jl
  src/backends/gaston.jl
  src/examples.jl
Labels: enhancement
