Repository JuliaPlots/Plots.jl, pull requests merged in 2022-12, with the labels that each got.

#4542 initial port of `pyplot` to `pythonplot`
  .github/workflows/ci.yml
  Project.toml
  src/backends.jl
  src/backends/pyplot.jl
  src/backends/pythonplot.jl
  src/examples.jl
  src/init.jl
  test/test_backends.jl
Labels: extension, PythonPlot

#4578 ref imgs: try to checkout a tag
  Project.toml
  test/test_backends.jl
Labels: bug, CI

#4566 select `Plots` backend via `Preferences` (or env variable)
  .github/workflows/ci.yml
  Project.toml
  src/Plots.jl
  src/backends.jl
  src/backends/deprecated/pyplot.jl
  src/backends/gr.jl
  src/backends/pgfplotsx.jl
  src/backends/plotly.jl
  src/backends/plotlyjs.jl
  src/backends/pythonplot.jl
  src/backends/web.jl
  src/examples.jl
  src/ijulia.jl
  src/init.jl
  src/precompile.jl
  src/utils.jl
  test/runtests.jl
  test/test_axes.jl
  test/test_backends.jl
  test/test_misc.jl
  test/test_output.jl
  test/test_quality.jl
Labels: enhancement, ttfp

#4575 consider only visible data/sample all
  src/utils.jl
  test/test_utils.jl
Labels: enhancement

#4584 fix plotly incongruity
  src/Plots.jl
  src/backends.jl
  src/backends/plotly.jl
  src/backends/plotlyjs.jl
  src/init.jl
  test/test_output.jl
Labels: Plotly, regression

#4588 restore inset bbox
  src/layouts.jl
Labels: bug, PGFPlotsX, regression

#4592 fix macro
  src/backends.jl
Labels: bug, regression

#4609 Gaston: Int32 / Int64
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  src/backends/gaston.jl
  test/test_quality.jl
Labels: enhancement, Gaston
