Repository JuliaPlots/Plots.jl, pull requests merged in 2022-07, with the labels that each got.

#4265 fix annotations
  .github/workflows/SnoopCompile.yml
  .github/workflows/benchmark.yml
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .github/workflows/format_check.yml
  .github/workflows/format_pr.yml
  Project.toml
  src/Plots.jl
  test/runtests.jl
  test/test_backends.jl
  test/test_shorthands.jl
Labels: bug, CI

#4263 Sanitize symbol and nothing Comparisons
  deps/SnoopCompile/precompile/1.6/precompile_Plots.jl
  deps/SnoopCompile/precompile/1.7/precompile_Plots.jl
  src/animation.jl
  src/args.jl
  src/axes.jl
  src/backends.jl
  src/backends/deprecated/pgfplots.jl
  src/backends/gaston.jl
  src/backends/gr.jl
  src/backends/inspectdr.jl
  src/backends/pgfplotsx.jl
  src/backends/plotly.jl
  src/backends/pyplot.jl
  src/colorbars.jl
  src/components.jl
  src/examples.jl
  src/ijulia.jl
  src/layouts.jl
  src/output.jl
  src/pipeline.jl
  src/recipes.jl
  src/utils.jl
  test/test_components.jl
  test/test_contours.jl
  test/test_defaults.jl
  test/test_layouts.jl
  test/test_misc.jl
  test/test_pgfplotsx.jl
  test/test_recipes.jl
  test/test_shorthands.jl
Labels: formatting, load / precompilation

#4262 PGFPlotsX: reworks
  Project.toml
  src/axes.jl
  src/backends/pgfplotsx.jl
  src/colorbars.jl
  test/runtests.jl
  test/test_animations.jl
  test/test_axes.jl
  test/test_backends.jl
  test/test_components.jl
  test/test_dates.jl
  test/test_defaults.jl
  test/test_hdf5plots.jl
  test/test_layouts.jl
  test/test_output.jl
  test/test_pgfplotsx.jl
  test/test_plotly.jl
  test/test_shorthands.jl
  test/test_utils.jl
Labels: bug, PGFPlotsX

#4283 gr: support `:pixel`
  src/backends.jl
  src/backends/gr.jl
Labels: enhancement, GR

#4286 pgfplotsx: fix misplaced `return nothing`
  src/backends/pgfplotsx.jl
  test/test_pgfplotsx.jl
Labels: bug, PGFPlotsX

#4297 annotate! relative position independant from the axis scale
  src/components.jl
Labels: enhancement
