Repository JuliaPlots/Plots.jl, pull requests merged in 2022-08, with the labels that each got.

#4300 added colorbartitle attributes for pgfplotsx
  src/backends/pgfplotsx.jl
Labels: PGFPlotsX

#4295 Add APNG animation support
  src/animation.jl
  src/utils.jl
  test/test_animations.jl
Labels: extension

#4291 Allow user to specify series type for line of `areaplot`
  src/recipes.jl
Labels: enhancement

#4307 Fix annotate! API, add test coverage
  src/Plots.jl
  test/test_shorthands.jl
Labels: bug

#4310 `pgfplotsx`: fix tex labels already in `mathmode` form
  src/backends/pgfplotsx.jl
  test/test_pgfplotsx.jl
Labels: bug, PGFPlotsX

#4309 Make `savefig` filepath-type agnostic
  Project.toml
  src/output.jl
  test/runtests.jl
  test/test_output.jl
Labels: extension
