Repository JuliaPlots/Plots.jl, pull requests merged in 2022-10, with the labels that each got.

#4411 Refactor to reduce allocations in `slice_arg!`
  src/args.jl
Labels: performance

#4412 Faster extrema calculations for large series
  src/axes.jl
  src/pipeline.jl
Labels: performance

#4410 Title location and alignment
  src/backends/gr.jl
  src/backends/pgfplotsx.jl
  src/backends/plotly.jl
Labels: bug, GR, Plotly, PGFPlotsX

#4414 Unitful ticks and lims
  .zenodo.json
  src/axes.jl
  src/colorbars.jl
  src/unitful.jl
  test/test_unitful.jl
Labels: UnitfulRecipes

#4367 Scaling axis limits by manual factor
  src/arg_desc.jl
  src/axes.jl
  src/pipeline.jl
  src/recipes.jl
  test/test_axes.jl
Labels: extension

#4420 Set default theme by default
  src/init.jl
Labels: bug

#4421 Don't assume aspect ratio if none given
  src/unitful.jl
  test/test_unitful.jl
Labels: bug, UnitfulRecipes

#4423 drop `StatsBase` 0.32
  Project.toml
Labels: bug, load / precompilation, upstream

#4419 integrate `RecipesBase` and `RecipesPipeline` into `Plots`
  .github/workflows/ci.yml
  RecipesBase/LICENSE.md
  RecipesBase/Project.toml
  RecipesBase/README.md
  RecipesBase/src/RecipesBase.jl
  RecipesBase/test/runtests.jl
  RecipesPipeline/LICENSE
  RecipesPipeline/Project.toml
  RecipesPipeline/README.md
  RecipesPipeline/deps/SnoopCompile/precompile/1.6/precompile_RecipesPipeline.jl
  RecipesPipeline/deps/SnoopCompile/precompile/1.7/precompile_RecipesPipeline.jl
  RecipesPipeline/deps/SnoopCompile/precompile/precompile_RecipesPipeline.jl
  RecipesPipeline/deps/SnoopCompile/snoop_bench.jl
  RecipesPipeline/deps/SnoopCompile/snoop_bot.jl
  RecipesPipeline/src/RecipesPipeline.jl
  RecipesPipeline/src/api.jl
  RecipesPipeline/src/group.jl
  RecipesPipeline/src/plot_recipe.jl
  RecipesPipeline/src/precompile_includer.jl
  RecipesPipeline/src/recipes.jl
  RecipesPipeline/src/series.jl
  RecipesPipeline/src/series_recipe.jl
  RecipesPipeline/src/type_recipe.jl
  RecipesPipeline/src/user_recipe.jl
  RecipesPipeline/src/utils.jl
  RecipesPipeline/test/runtests.jl
  RecipesPipeline/test/test_group.jl
Labels: upstream, nfc, RecipesBase, RecipesPipeline

#4446 format `RecipesBase` and `RecipesPipeline`
  RecipesBase/src/RecipesBase.jl
  RecipesBase/test/runtests.jl
  RecipesPipeline/src/RecipesPipeline.jl
  RecipesPipeline/src/api.jl
  RecipesPipeline/src/group.jl
  RecipesPipeline/src/plot_recipe.jl
  RecipesPipeline/src/precompile_includer.jl
  RecipesPipeline/src/recipes.jl
  RecipesPipeline/src/series.jl
  RecipesPipeline/src/series_recipe.jl
  RecipesPipeline/src/type_recipe.jl
  RecipesPipeline/src/user_recipe.jl
  RecipesPipeline/src/utils.jl
  RecipesPipeline/test/runtests.jl
  RecipesPipeline/test/test_group.jl
Labels: formatting, nfc

#4447 `RecipesPipeline`: generate precomp statements using `SnoopPrecompile`
  RecipesPipeline/Project.toml
  RecipesPipeline/deps/SnoopCompile/precompile/1.6/precompile_RecipesPipeline.jl
  RecipesPipeline/deps/SnoopCompile/precompile/1.7/precompile_RecipesPipeline.jl
  RecipesPipeline/deps/SnoopCompile/precompile/precompile_RecipesPipeline.jl
  RecipesPipeline/deps/SnoopCompile/snoop_bench.jl
  RecipesPipeline/deps/SnoopCompile/snoop_bot.jl
  RecipesPipeline/src/RecipesPipeline.jl
  RecipesPipeline/src/group.jl
  RecipesPipeline/src/plot_recipe.jl
  RecipesPipeline/src/precompile_includer.jl
Labels: load / precompilation, RecipesPipeline

#4448 fix spurious warning (precomp)
  src/axes.jl
  src/backends.jl
Labels: bug, regression

#4449 use `circshift` instead of `axes_shift`
  src/axes.jl
  src/backends/gr.jl
Labels: enhancement, GR, nfc

#4452 bump `GR`
  Project.toml
Labels: GR

#4450 Fix last marker bug
  .zenodo.json
  src/backends/plotly.jl
Labels: bug, Plotly, PlotlyJS, first PR

#4454 bump `RB` & `RP` coverage
  .github/workflows/ci.yml
  RecipesBase/Project.toml
  RecipesBase/src/RecipesBase.jl
  RecipesBase/test/runtests.jl
  RecipesPipeline/src/RecipesPipeline.jl
  RecipesPipeline/src/group.jl
  RecipesPipeline/src/utils.jl
  RecipesPipeline/test/runtests.jl
Labels: RecipesBase, RecipesPipeline, coverage

#4455 more coverage
  RecipesBase/src/RecipesBase.jl
  RecipesBase/test/runtests.jl
  RecipesPipeline/Project.toml
  RecipesPipeline/src/utils.jl
  RecipesPipeline/test/runtests.jl
  RecipesPipeline/test/test_group.jl
Labels: RecipesBase, RecipesPipeline, coverage

#4456 add quality test using `Aqua`
  Project.toml
  RecipesBase/src/RecipesBase.jl
  src/Plots.jl
  src/args.jl
  src/axes.jl
  src/backends.jl
  src/backends/gaston.jl
  src/backends/hdf5.jl
  src/backends/pgfplotsx.jl
  src/backends/plotly.jl
  src/backends/pyplot.jl
  src/examples.jl
  src/init.jl
  src/precompile.jl
  src/recipes.jl
  src/utils.jl
  test/runtests.jl
  test/test_args.jl
  test/test_backends.jl
  test/test_layouts.jl
  test/test_quality.jl
  test/test_utils.jl
Labels: CI, deadcode, coverage

#4459 RB: remove debug support (macro instead)
  RecipesBase/README.md
  RecipesBase/src/RecipesBase.jl
  RecipesBase/test/runtests.jl
Labels: performance, RecipesBase

#4460 bump RP coverage
  RecipesPipeline/src/series.jl
  test/test_recipes.jl
Labels: RecipesPipeline, coverage

#4461 bump coverage
  src/animation.jl
  src/args.jl
  src/backends.jl
  src/backends/deprecated/pgfplots.jl
  src/plot.jl
  src/types.jl
  src/utils.jl
  test/test_animations.jl
  test/test_args.jl
  test/test_backends.jl
  test/test_misc.jl
  test/test_pgfplotsx.jl
Labels: nfc, coverage

#4462 add downstream tests to coverage
  .github/workflows/ci.yml
Labels: CI, coverage

#4466 fix `nightly` - bump cov
  src/args.jl
  src/axes.jl
  src/backends.jl
  src/backends/hdf5.jl
  src/backends/inspectdr.jl
  src/backends/plotly.jl
  src/backends/pyplot.jl
  src/backends/web.jl
  src/examples.jl
  src/output.jl
  src/recipes.jl
  src/utils.jl
  test/test_args.jl
  test/test_backends.jl
  test/test_misc.jl
  test/test_output.jl
  test/test_plotly.jl
  test/test_utils.jl
Labels: PyPlot, Plotly, CI, hdf5, coverage

#4469 bump cov - more `PyPlot` exs
  src/animation.jl
  src/axes.jl
  src/backends/gr.jl
  src/components.jl
  src/examples.jl
  src/recipes.jl
  test/test_animations.jl
  test/test_axes.jl
  test/test_components.jl
  test/test_misc.jl
  test/test_shorthands.jl
  test/test_utils.jl
Labels: PyPlot, coverage

#4470 restore non-allocating generator - bump coverage
  RecipesBase/src/RecipesBase.jl
  RecipesPipeline/src/series_recipe.jl
  src/animation.jl
  src/args.jl
  src/axes.jl
  src/backends.jl
  src/backends/deprecated/pgfplots.jl
  src/backends/gaston.jl
  src/backends/gr.jl
  src/backends/hdf5.jl
  src/backends/inspectdr.jl
  src/backends/pgfplotsx.jl
  src/backends/plotly.jl
  src/backends/pyplot.jl
  src/backends/unicodeplots.jl
  src/backends/web.jl
  src/components.jl
  src/examples.jl
  src/layouts.jl
  src/output.jl
  src/pipeline.jl
  src/plot.jl
  src/recipes.jl
  src/themes.jl
  src/unitful.jl
  src/utils.jl
  templates/backends.jl
  test/test_axes.jl
  test/test_backends.jl
  test/test_components.jl
  test/test_layouts.jl
  test/test_misc.jl
  test/test_output.jl
  test/test_pgfplotsx.jl
  test/test_recipes.jl
  test/test_unitful.jl
Labels: CI, deadcode, nfc, coverage

#4472 bump coverage
  src/animation.jl
  src/args.jl
  src/axes.jl
  src/backends.jl
  src/backends/gr.jl
  src/backends/unicodeplots.jl
  src/components.jl
  src/consts.jl
  src/layouts.jl
  src/recipes.jl
  src/types.jl
  src/utils.jl
  test/test_animations.jl
  test/test_axes.jl
  test/test_backends.jl
  test/test_components.jl
  test/test_layouts.jl
  test/test_misc.jl
  test/test_output.jl
  test/test_recipes.jl
  test/test_utils.jl
Labels: nfc, coverage

#4480 simplify `GRViewport`
  src/backends/gr.jl
  src/components.jl
  test/test_components.jl
Labels: GR, nfc

#4482 collect `skipmissing`
  RecipesPipeline/src/series.jl
  RecipesPipeline/test/runtests.jl
  test/test_misc.jl
Labels: bug, RecipesPipeline

#4479 eachindex call incorrectly assumes that the returned index is IndexLinear
  Project.toml
  src/backends/gr.jl
  test/runtests.jl
  test/test_utils.jl
Labels: bug

#4483 add `:none` formatter
  src/arg_desc.jl
  src/axes.jl
  src/utils.jl
  test/test_axes.jl
  test/test_utils.jl
Labels: enhancement
