Repository JuliaPlots/Plots.jl, pull requests merged in 2022-09, with the labels that each got.

#4320 3d: add `projection_type`
  .github/workflows/SnoopCompile.yml
  .github/workflows/ci.yml
  src/Plots.jl
  src/arg_desc.jl
  src/args.jl
  src/backends/gr.jl
  src/backends/plotly.jl
  src/backends/pyplot.jl
  src/backends/unicodeplots.jl
  src/examples.jl
  src/layouts.jl
  src/output.jl
  src/pipeline.jl
  src/plot.jl
  src/subplots.jl
  src/types.jl
  src/utils.jl
  test/test_backends.jl
  test/test_misc.jl
Labels: GR, PyPlot, UnicodePlots, PlotlyJS, extension

#4329 format: function declaration (nfc)
  .JuliaFormatter.toml
  src/args.jl
  src/axes.jl
  src/backends.jl
  src/backends/deprecated/pgfplots.jl
  src/backends/plotly.jl
  src/backends/plotlyjs.jl
  src/backends/pyplot.jl
  src/backends/web.jl
  src/consts.jl
  src/layouts.jl
  src/recipes.jl
Labels: formatting, nfc

#4330 fix `h5` Extrema
  src/types.jl
  test/test_hdf5plots.jl
Labels: bug, hdf5

#4331 `pyplot`: fix var shadowing - fix docs build
  src/backends/pyplot.jl
Labels: bug, PyPlot

#4011 support `unicodeplots` images - plot in term `ImageInTerminal - Sixel`
  src/backends.jl
  src/backends/unicodeplots.jl
  src/examples.jl
  src/init.jl
  src/output.jl
Labels: GR, UnicodePlots, extension

#4335 increase default `(minor)gridalpha`
  src/args.jl
Labels: GR

#4342 fix legend of plotly and plotyjs
  src/backends/plotly.jl
Labels: Plotly, PlotlyJS

#4339 add docstrings to Density function
  src/shorthands.jl
Labels: documentation - API

#4343 Extended help to show all attributes
  src/consts.jl
  src/plot.jl
Labels: discussion, documentation - API

#4328 Fixed missing marker in legend when plotting a series whose first entry is NaN
  src/backends/gr.jl
Labels: bug, GR

#4341 use PlotlyKaleido for saving in plotly backend
  Project.toml
  src/backends.jl
  src/backends/plotlybase.jl
  src/init.jl
Labels: Plotly

#4344 fix setting default font via `font`
  deps/SnoopCompile/precompile/1.6/precompile_Plots.jl
  deps/SnoopCompile/precompile/1.7/precompile_Plots.jl
  deps/SnoopCompile/precompile/1.8/precompile_Plots.jl
  src/args.jl
  src/axes.jl
  src/pipeline.jl
  src/plot.jl
  src/utils.jl
  test/test_args.jl
  test/test_contours.jl
  test/test_defaults.jl
Labels: bug

#4348 Updated `pgfplotsx.jl` to use correct variable names
  src/backends/pgfplotsx.jl
  test/test_pgfplotsx.jl
Labels: bug, PGFPlotsX

#4356 rework `gr_draw_markers` for 3d - fix ticks labels (flip)
  src/backends/gr.jl
  test/test_misc.jl
Labels: bug, GR

#4357 nfc: syntax
  src/backends/gr.jl
Labels: GR

#4380 safer clone
  test/test_backends.jl
Labels: CI

#4378 fix single `:auto` in `xlims` or `ylims`
  src/axes.jl
  test/test_axes.jl
Labels: bug

#4371 Integrate `UnitfulRecipes` into `Plots`
  Project.toml
  src/Plots.jl
  src/animation.jl
  src/backends/pgfplotsx.jl
  src/init.jl
  src/plotmeasures.jl
  src/precompilation.jl
  src/types.jl
  src/unitful.jl
  test/runtests.jl
  test/test_defaults.jl
  test/test_misc.jl
  test/test_recipes.jl
  test/test_unitful.jl
Labels: bug, enhancement

#4383 restore `Symbol` label support
  src/backends/gr.jl
  test/test_axes.jl
Labels: bug, regression

#4392 dont warn on lim numeric values
  src/axes.jl
Labels: regression

#4395 Remove obsolete `GR` warning
  src/backends/gr.jl
Labels: GR

#4402 use `withenv` instead of persistent `ENV` variables
  src/backends/gr.jl
Labels: enhancement, GR

#4406 add precompilation workaround for `windows` on julia `1.8.2`
  src/precompilation.jl
Labels: load / precompilation, windows
