Repository JuliaPlots/Plots.jl, pull requests merged in 2022-11, with the labels that each got.

#4486 Legend fix
  RecipesBase/src/RecipesBase.jl
  RecipesBase/test/runtests.jl
  RecipesPipeline/src/group.jl
  RecipesPipeline/src/plot_recipe.jl
  RecipesPipeline/src/series.jl
  RecipesPipeline/src/user_recipe.jl
  src/backends/gr.jl
Labels: bug, GR, regression

#4487 fix `twinx` ticks
  src/backends/gr.jl
  src/layouts.jl
Labels: bug

#4488 fix inset padding
  RecipesPipeline/src/utils.jl
  src/Plots.jl
  src/args.jl
  src/backends/gaston.jl
  src/backends/gr.jl
  src/backends/inspectdr.jl
  src/examples.jl
  src/layouts.jl
  src/plot.jl
  test/test_backends.jl
Labels: bug, enhancement, extension, layout

#4492 fix `gr` legend
  src/axes.jl
  src/backends/gr.jl
  src/backends/inspectdr.jl
  src/layouts.jl
Labels: GR, regression, upstream

#4493 `unicodeplots`: transpose `surfaceplot` z - support `xflip` and `yflip`
  src/backends/unicodeplots.jl
Labels: enhancement, UnicodePlots

#4495 `twin`: fix `framestyle` issue and `grid`
  src/backends/pyplot.jl
  src/layouts.jl
Labels: GR, PyPlot

#4496 `gr`: support horizontal legends
  src/backends/gr.jl
  src/examples.jl
  src/layouts.jl
  src/utils.jl
  test/runtests.jl
  test/test_backends.jl
  test/test_misc.jl
Labels: bug, GR, extension

#4498 `pyplot`: support `legend_column`
  src/backends/pyplot.jl
  src/examples.jl
Labels: enhancement, PyPlot

#4501 Support transposed images
  src/utils.jl
Labels: bug, Plotly

#4503 baseline fix for bar plots using log scales
  src/args.jl
  src/pipeline.jl
  src/recipes.jl
  src/shorthands.jl
  src/utils.jl
  test/test_misc.jl
  test/test_output.jl
  test/test_pgfplotsx.jl
  test/test_recipes.jl
  test/test_unitful.jl
Labels: bug, awesome log scales

#4510 fix non square `unicodeplots` layout
  src/args.jl
  src/backends/unicodeplots.jl
  src/utils.jl
Labels: bug, UnicodePlots

#4512 Add layout test - Add `png` warning on failing font
  src/backends/unicodeplots.jl
  test/test_backends.jl
  test/test_output.jl
Labels: UnicodePlots, CI

#4524 fix spurious warning
  RecipesPipeline/src/RecipesPipeline.jl
  RecipesPipeline/src/api.jl
  RecipesPipeline/src/type_recipe.jl
  RecipesPipeline/src/user_recipe.jl
  src/args.jl
Labels: bug, RecipesPipeline

#4523 allow `Tuple`s for `margin`s
  src/arg_desc.jl
  src/args.jl
  src/recipes.jl
  test/test_args.jl
  test/test_backends.jl
Labels: extension, RecipesBase

#4525 Rework docstrings
  src/Plots.jl
  src/arg_desc.jl
  src/args.jl
  src/plotattr.jl
  src/shorthands.jl
  src/utils.jl
  test/test_misc.jl
  test/test_utils.jl
Labels: documentation - API

#4527 add `PlotDocs` note
  src/arg_desc.jl
  src/plotattr.jl
  src/utils.jl
Labels: documentation - API

#4529 enhance `plotattr`
  src/plotattr.jl
Labels: documentation - API

#4528 fix `minorticks`
  src/arg_desc.jl
  src/args.jl
  src/axes.jl
  src/backends/pgfplotsx.jl
  src/backends/pyplot.jl
  src/examples.jl
  src/types.jl
  test/test_axes.jl
  test/test_backends.jl
Labels: bug

#4530 multiply `legend_font_pointsize` by `line_width`
  src/args.jl
  src/backends/gr.jl
Labels: bug, GR

#4535 fix padding with inset plots
  src/args.jl
  src/backends/gr.jl
  src/backends/pyplot.jl
  src/examples.jl
  src/layouts.jl
  src/pipeline.jl
  src/plot.jl
  src/recipes.jl
  src/types.jl
  src/utils.jl
  test/test_backends.jl
  test/test_layouts.jl
  test/test_utils.jl
Labels: layout

#4537 Fix unitful axes with empty guides
  src/unitful.jl
  test/test_unitful.jl
  test/test_utils.jl
Labels: UnitfulRecipes

#4539 improve `heatmap_edges` performance
  src/axes.jl
  src/backends/plotly.jl
  src/utils.jl
  test/test_utils.jl
Labels: performance, nfc

#4541 enhance `gr` log scales - support `gaston` `contourf`
  src/backends.jl
  src/backends/gaston.jl
  src/backends/gr.jl
Labels: GR, Gaston, awesome log scales

#4543 add `empty!` for `Plot`s and `Subplot`s
  src/types.jl
  test/test_misc.jl
Labels: performance

#4536 implements best legend place holder
  src/backends/gr.jl
  src/utils.jl
  test/runtests.jl
  test/test_utils.jl
Labels: extension

#4548 add `num_minor_intervals` helper
  src/axes.jl
Labels: nfc

#4550 fix docs
  src/utils.jl
  test/test_utils.jl
Labels: bug, documentation - API

#4551 do not draw tick labels when `showaxis` set to `false`
  src/backends/gr.jl
Labels: GR

#4552 remove duplicate `alias`es
  src/args.jl
Labels: nfc

#4553 `gaston`: general improvements
  src/backends/gaston.jl
  src/backends/gr.jl
  src/components.jl
  src/examples.jl
  test/test_backends.jl
Labels: Gaston

#4554 pad ref images
  test/test_backends.jl
Labels: nfc

#4555 fix legend title align
  src/backends/gr.jl
Labels: GR, regression

#4558 support scale in `get_...color`
  src/utils.jl
Labels: extension

#4560 adjust tests for `PkgEval`
  test/runtests.jl
  test/test_backends.jl
Labels: CI

#4564 Fix polar heatmap bounds
  src/arg_desc.jl
  src/args.jl
  src/backends/gr.jl
  src/examples.jl
  test/runtests.jl
  test/test_misc.jl
Labels: bug, GR

#4559 [RecipesBase] Use interpolation instead of qualification to drop dependance on the namespace of RecipesBase users
  RecipesBase/src/RecipesBase.jl
  RecipesBase/test/runtests.jl
Labels: enhancement, RecipesBase

#4569 Make plotly colorbar size scale with plot size
  src/backends/plotly.jl
Labels: enhancement, Plotly

#4570 bump `RecipesBase`
  RecipesBase/Project.toml
  RecipesBase/src/RecipesBase.jl
  src/backends/plotly.jl
Labels: formatting, RecipesBase

#4572 fix spurious gaston ticks integer overflow
  src/backends/gaston.jl
Labels: enhancement, Gaston

#4574 fix gaston bug
  src/backends/gaston.jl
Labels: bug, Gaston
